/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package curriculumdigital.gui;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import curriculumdigital.core.Curriculo;
import curriculumdigital.core.Submission;
import curriculumdigital.core.User;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.io.File;
import java.io.IOException;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.List;
import javax.swing.SwingUtilities;

/**
 *
 * @author noemi
 */
public class GUI extends javax.swing.JFrame {

    public static String fileCurriculo = "curriculo.obj";
    Curriculo curriculo ;
    List<Submission> elements = new ArrayList();

    User myUser = null;

    /**
     * Creates new form Interface
     */
    public GUI() {
        initComponents();
        setTitle("Curriculum Digital");
        try {

            File file = new File("blockchainfiles", fileCurriculo);

            if (file.exists()) {
                curriculo = Curriculo.load(fileCurriculo);
                elements.addAll(curriculo.submissions);
                txtCV.setText(curriculo.toString());
//                txtCV.setText(elements.toString());
                curriculo.submissions.clear();
                textAreaCVAll.setText(curriculo.loadPersonEvents(null, true));
            } else {
                curriculo = new Curriculo();
            }
        } catch (Exception e) {
            System.out.print(e);
        }
        setSize(800, 500);
        setLocationRelativeTo(null);

        this.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent we) {
                if (!curriculo.submissions.isEmpty()) {
                    try {
                        curriculo.save(fileCurriculo, true);
                    } catch (IOException ex) {
                        Logger.getLogger(GUI.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
        });
    }

    public GUI(User u) {
        this();
        this.myUser = u;

        this.txtInstitute.setText(u.getName());

        if (!u.isInstitute()) {
            // Remover o Tab "Curriculum" para utilizadores não institucionais
            App.remove(Curriculum); // Remove a aba do Curriculum
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        App = new javax.swing.JTabbedPane();
        Curriculum = new javax.swing.JPanel();
        lbCurriculum = new javax.swing.JLabel();
        ScrollInstitute = new javax.swing.JScrollPane();
        txtInstitute = new javax.swing.JTextField();
        ScrollName = new javax.swing.JScrollPane();
        txtName = new javax.swing.JTextField();
        ScrollEvent = new javax.swing.JScrollPane();
        txtEvent = new javax.swing.JTextArea();
        btnAdd = new javax.swing.JButton();
        ScrollCV = new javax.swing.JScrollPane();
        txtCV = new javax.swing.JTextArea();
        ListaPessoas = new javax.swing.JPanel();
        btnPersonCV = new javax.swing.JButton();
        txtNameCV = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        textAreaCVPerson = new javax.swing.JTextArea();
        lbSearchCurriculum = new javax.swing.JLabel();
        ListaCurriculum = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textAreaCVAll = new javax.swing.JTextArea();
        lbAllCurriculum = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbCurriculum.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbCurriculum.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbCurriculum.setText("Curriculum Digital");

        ScrollInstitute.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        txtInstitute.setEditable(false);
        txtInstitute.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Instituto", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        ScrollInstitute.setViewportView(txtInstitute);

        ScrollName.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        txtName.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nome", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        ScrollName.setViewportView(txtName);

        ScrollEvent.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        ScrollEvent.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        txtEvent.setColumns(20);
        txtEvent.setLineWrap(true);
        txtEvent.setRows(5);
        txtEvent.setWrapStyleWord(true);
        txtEvent.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Evento", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        ScrollEvent.setViewportView(txtEvent);

        btnAdd.setText("Adicionar");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        ScrollCV.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        txtCV.setEditable(false);
        txtCV.setColumns(20);
        txtCV.setLineWrap(true);
        txtCV.setRows(5);
        txtCV.setWrapStyleWord(true);
        ScrollCV.setViewportView(txtCV);

        javax.swing.GroupLayout CurriculumLayout = new javax.swing.GroupLayout(Curriculum);
        Curriculum.setLayout(CurriculumLayout);
        CurriculumLayout.setHorizontalGroup(
            CurriculumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbCurriculum, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(CurriculumLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(CurriculumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnAdd, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 311, Short.MAX_VALUE)
                    .addComponent(ScrollInstitute, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ScrollName)
                    .addComponent(ScrollEvent))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(ScrollCV, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );
        CurriculumLayout.setVerticalGroup(
            CurriculumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CurriculumLayout.createSequentialGroup()
                .addComponent(lbCurriculum, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addGroup(CurriculumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CurriculumLayout.createSequentialGroup()
                        .addComponent(ScrollInstitute, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ScrollName, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ScrollEvent, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(ScrollCV, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(225, 225, 225))
        );

        App.addTab("Curriculum", Curriculum);

        btnPersonCV.setText("Procurar");
        btnPersonCV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPersonCVActionPerformed(evt);
            }
        });

        txtNameCV.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nome da Pessoa", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        textAreaCVPerson.setEditable(false);
        textAreaCVPerson.setColumns(20);
        textAreaCVPerson.setLineWrap(true);
        textAreaCVPerson.setRows(5);
        textAreaCVPerson.setWrapStyleWord(true);
        jScrollPane2.setViewportView(textAreaCVPerson);

        lbSearchCurriculum.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbSearchCurriculum.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbSearchCurriculum.setText("Procurar Curriculum");

        javax.swing.GroupLayout ListaPessoasLayout = new javax.swing.GroupLayout(ListaPessoas);
        ListaPessoas.setLayout(ListaPessoasLayout);
        ListaPessoasLayout.setHorizontalGroup(
            ListaPessoasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ListaPessoasLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(ListaPessoasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtNameCV, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
                    .addComponent(btnPersonCV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(72, 72, 72)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(lbSearchCurriculum, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );
        ListaPessoasLayout.setVerticalGroup(
            ListaPessoasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ListaPessoasLayout.createSequentialGroup()
                .addComponent(lbSearchCurriculum, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ListaPessoasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ListaPessoasLayout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(txtNameCV, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnPersonCV, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(270, Short.MAX_VALUE))
        );

        App.addTab("Lista Pessoas", ListaPessoas);

        textAreaCVAll.setEditable(false);
        textAreaCVAll.setColumns(20);
        textAreaCVAll.setLineWrap(true);
        textAreaCVAll.setRows(5);
        textAreaCVAll.setWrapStyleWord(true);
        jScrollPane1.setViewportView(textAreaCVAll);

        lbAllCurriculum.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbAllCurriculum.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbAllCurriculum.setText("Todos os Curriculums");

        javax.swing.GroupLayout ListaCurriculumLayout = new javax.swing.GroupLayout(ListaCurriculum);
        ListaCurriculum.setLayout(ListaCurriculumLayout);
        ListaCurriculumLayout.setHorizontalGroup(
            ListaCurriculumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ListaCurriculumLayout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 610, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(99, Short.MAX_VALUE))
            .addComponent(lbAllCurriculum, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );
        ListaCurriculumLayout.setVerticalGroup(
            ListaCurriculumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ListaCurriculumLayout.createSequentialGroup()
                .addComponent(lbAllCurriculum, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(270, Short.MAX_VALUE))
        );

        App.addTab("Lista Curriculum", ListaCurriculum);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(App, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(App)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPersonCVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPersonCVActionPerformed
        try {
            textAreaCVPerson.setText("");
            String s = curriculo.loadPersonEvents(txtNameCV.getText(), false);
            if (!"".equals(s)) {
                textAreaCVPerson.setText(s);
            } else if("".equals(txtNameCV.getText())) {
                JOptionPane.showMessageDialog(this, "Coloca o nome da pessoa que queres procurar.", "Coloca o nome!", JOptionPane.ERROR_MESSAGE);
            } else {
                // Mostra uma mensagem de erro no caso de não haver essa pessoa
                JOptionPane.showMessageDialog(this, "Não existem currículos dessa pessoa.", "Não existe!", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
            Logger.getLogger(GUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnPersonCVActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        btnAdd.setEnabled(false);
        new Thread(() -> {
            try {
                // Verifica se o utilizador é uma instituição
                if (myUser.isInstitute()) {
                    // Cria a submissão normalmente se o utilizador for uma instituição
                    Submission s = new Submission(
                        myUser,
                        txtName.getText(),
                        txtEvent.getText()
                    );

                    // Adiciona a submissão ao currículo e atualiza o campo de texto
                    curriculo.add(s);
                    elements.add(s);
                    SwingUtilities.invokeLater(() -> {
                        txtCV.setText(curriculo.submissions.toString());
                        btnAdd.setEnabled(true);
                    });
                    curriculo.save(fileCurriculo, false);
                } else {
                    // Mostra uma mensagem de erro caso o utilizador não seja uma instituição
                    JOptionPane.showMessageDialog(this, "Apenas Instituições podem adicionar submissões.", "Acesso Negado", JOptionPane.WARNING_MESSAGE);
                }
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage());
                Logger.getLogger(GUI.class.getName()).log(Level.SEVERE, null, ex);
            }
        }).start();
    }//GEN-LAST:event_btnAddActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane App;
    private javax.swing.JPanel Curriculum;
    private javax.swing.JPanel ListaCurriculum;
    private javax.swing.JPanel ListaPessoas;
    private javax.swing.JScrollPane ScrollCV;
    private javax.swing.JScrollPane ScrollEvent;
    private javax.swing.JScrollPane ScrollInstitute;
    private javax.swing.JScrollPane ScrollName;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnPersonCV;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbAllCurriculum;
    private javax.swing.JLabel lbCurriculum;
    private javax.swing.JLabel lbSearchCurriculum;
    private javax.swing.JTextArea textAreaCVAll;
    private javax.swing.JTextArea textAreaCVPerson;
    private javax.swing.JTextArea txtCV;
    private javax.swing.JTextArea txtEvent;
    private javax.swing.JTextField txtInstitute;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtNameCV;
    // End of variables declaration//GEN-END:variables
}
